[package]
name = "rustc_bug_repro"
version = "0.1.0"
authors = ["Demi Marie Obenour <demiobenour@gmail.com>"]
repository = "https://github.com/DemiMarie/RustyScheme"
readme = "README.md"
license = "MIT/Apache 2.0"
